### ISSUE TITLE
LOGO PROPOSAL FOR Firebase.Notification

### ISSUE THREAD

**Issue by orlant** [frankodoom/Firebase.Notification#1]
Hi, I'm a graphic designer, how are you? a pleasure to greet you, I like to make contributions to projects like yours, since digital art is very important in projects, if you allow me I can make some logo ideas so you can use the one you like the most

**Comment by frankodoom** [comment]
Sure @orlant you are much welcome

**Comment by orlant** [comment]
thank you very much from now I will start to make some sketches. The concept that I will use for your design will be a minimalist icon. Since it is a library to send notifications and it would be ideal, do you have any other information that I should take into account for this design?

**Comment by frankodoom** [comment]
Not really I will leave the creative aspect to you.

**Comment by orlant** [comment]
ok then I will do my creative work ... I will come back when I digitize the idea that I have. see you soon

**Comment by frankodoom** [comment]
Sure. Thanks

**Comment by orlant** [comment]
Mr. Frankodoom taking into account that your project is based on a notification system. work based on an ICON design that with only one view can represent the image of Firebase.Notification. Below I show you...

![firebase banners](https://user-images.githubusercontent.com/40074778/42170212-eb377f80-7de3-11e8-8650-8c71200b7acb.png)

The result of this icon was inspired by the combination of the element of fire, which is related to a part of the composition of the name of the project and a bell representing the word notification. look I hope you like it

![firebase logo](https://user-images.githubusercontent.com/40074778/42170397-68bbc362-7de4-11e8-9296-02368387fdd4.jpg)
![2](https://user-images.githubusercontent.com/40074778/42170419-7533d67a-7de4-11e8-8798-7c09ea19fe4a.png)
![1](https://user-images.githubusercontent.com/40074778/42170434-7c7f928e-7de4-11e8-94a9-6cbfea96b7f2.png)


Now if you want I can use the icon model and create the logo with a font style of your liking. I would only show you some guys so that you can choose tell me what you think of the main idea ??

**Comment by frankodoom** [comment]
This is impressive I like the concept

**Comment by orlant** [comment]
I will show you what the logo looks like tell me if you want to have some different sources or prefer to keep the Icon concept?

**Comment by orlant** [comment]
Here is the LOGO and some different sources, but my suggestion is still the icon.

![textos](https://user-images.githubusercontent.com/40074778/42192582-b80438d4-7e37-11e8-8033-943e1d0414bd.png)

 Now if you can tell me what would be the winning logo model and the color ?? There are two models: logo enclosed in a circle like this...

![png 1](https://user-images.githubusercontent.com/40074778/42192600-d21d5fca-7e37-11e8-89c7-a43763884f9e.png)


logo in rounded square ...

![degradado2](https://user-images.githubusercontent.com/40074778/42192629-0406d64c-7e38-11e8-9152-abc76af04dd1.png)


I am anxious to know what the winning design will be and what will you use? to send you all the files

**Comment by frankodoom** [comment]
I think the last icon concept is good to go if we can have it in flaming colors, like yellow or orange just like the firebase logo. Then we good to go

**Comment by orlant** [comment]
perfect the orange and yellow gradient logo and you want what color do you want in the background?

**Comment by orlant** [comment]
![este](https://user-images.githubusercontent.com/40074778/42218894-05f3c7d4-7e98-11e8-8cae-d4d211334642.png)

Here are 4 different options more colors, keeping the main idea that you chose. !!! tell me what is the winner ???

**Comment by frankodoom** [comment]
Option 3 is best fit

**Comment by orlant** [comment]
I already sent the files to you!

**Comment by orlant** [comment]
NOW IF YOU HAVE ALREADY CHARGED ALL THE EDITABLE FILES READY FOR YOUR USE (PNG, EPS, SVG, AI, PDF, PSD) if you need anything else you can contact me. (if there is a project that needs a contribution let me know it would be a pleasure to help you, thank you very much).

[FILES](https://drive.google.com/open?id=116XetcBtP1p66geigMvcpUe3-ho7SDgh)

<a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Licencia Creative Commons" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a><br />Esta obra está bajo una <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Licencia Creative Commons Atribución 4.0 Internacional</a>.

**Comment by orlant** [comment]
Mr. Frank Here I bring you a design to use it as a cover.
![portada](https://user-images.githubusercontent.com/40074778/42230287-9bae2940-7eb6-11e8-8df1-44a9fcbebaa6.png)

**Comment by frankodoom** [comment]
The above is very nice, thank you for your contribution

**Comment by orlant** [comment]
always to order mister frank
